apiVersion: v1
kind: Service
metadata:
  name: nginxservice
spec:
  type: NodePort  
  selector:
    app: nginxpod
  ports:
    - protocol: TCP
      port: 80
      targetPort: nginxport  
      nodePort: 31010
