apiVersion: v1
kind: Pod
metadata:
  name: always-restart-pod
  labels:
    name: always-restart-pod
spec:
  restartPolicy: Always
  containers:
  - name: app
    image: alpine
    command: ["sleep","20"]



