apiVersion: v1
kind: Pod 
metadata:
  name: configmap-posix-demo
spec:
  containers:
    - name: configmap-posix
      image: anshuldevops/Kubernetes-web:1.10.6
      ports:
        - containerPort: 8080
      envForm:
        - configMapRef:
          name: player-posix-demo