apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-http
  labels:
    name: liveness-probe-http
spec:
  containers:
  - name: liveness-nginx
    image: k8s.gcr.io/nginx
    ports:
      - containerPort: 80
    startupProbe:
      httpGet:
        path: /
        port: 80
      failureThreshold: 30
      periodSeconds: 10
